### ISSUE TITLE
Error while initiating new chat in sample app

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/flutter-samples#4] opened 2021-02-12 09:01 UTC
<img width="443" alt="Screenshot 2021-02-12 at 1 45 13 PM" src="https://user-images.githubusercontent.com/21235425/107748061-78fa4680-6d3e-11eb-9dfa-3161d8c65749.png">

Issue:- In example app when I am clicking on the edit icon on the top right gives an error.

My Flutter Environment:- 
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)
```

**Comment by annshsingh** [comment] 2021-02-12 09:44
@hiashutoshsingh I fixed this by removing **IntrinsicHeight** wrapper and  the**crossAxisAlignment: CrossAxisAlignment.baseline** property in the **Row** widget inside **ChipsInputTextField** widget. 
At first I thought adding textBaseLine property would be sufficient for this to work (because of CrossAxisAlignment.baseline) but it did not work. 
Not sure what the main intention of the developer was here. 
@imtoori Please check. Thanks

**Comment by imtoori** [comment] 2021-02-12 09:46
Hey guys
The problem is that you are running the app using the beta channel of flutter while we developed it using the stable channel

**Comment by annshsingh** [comment] 2021-02-12 09:52
@imtoori Ohh, that's helpful. Would it be an issue if we plan on building our app on beta instead of stable? We don't plan on shifting to stable as we have to work on flutter web as well.

**Comment by imtoori** [comment] 2021-02-15 11:35
no problem at all I think
I'll make sure to fix this issue on the beta channel, but this is just a sample app so that's not a problem

**Comment by imtoori** [comment] 2021-03-04 08:54
fixed in the last release

**Closed by imtoori** 2021-03-04 08:54 UTC
